import {
  Bot,
  Copy,
  Check,
  User,
  Sparkles,
} from "lucide-react";

import { useState } from "react";
import ReactMarkdown from "react-markdown";

import SourcePanel from "../SourcePanel/SourcePanel";

import "./Message.css";


export default function Message({ message }) {

  const [copied, setCopied] = useState(false);

  const isUser = message.role === "user";

  async function copyMessage() {

    try {

      await navigator.clipboard.writeText(message.content);

      setCopied(true);

      setTimeout(() => setCopied(false), 1500);

    } catch {

      console.error("Unable to copy message.");

    }
  }

  return (
    <div
      className={`message-row ${
        isUser ? "user-message-row" : ""
      }`}
    >

      <div
        className={`message-avatar ${
          isUser ? "user-avatar" : "assistant-avatar"
        }`}
      >

        {isUser ? (
          <User size={17} />
        ) : (
          <Sparkles size={18} />
        )}

      </div>

      <div className="message-body">

        {!isUser && (
          <div className="message-header">

            <strong>Nexus</strong>

            {message.queryType && (
              <span
                className={`query-badge ${
                  message.queryType.toLowerCase()
                }`}
              >
                {message.queryType}
              </span>
            )}

          </div>
        )}

        <div
          className={`message-content ${
            message.isError ? "message-error" : ""
          }`}
        >

          {isUser ? (

            <p>
              {message.content}
            </p>

          ) : (

            <ReactMarkdown
              components={{
                code({
                  inline,
                  className,
                  children,
                }) {

                  return inline ? (

                    <code className={className}>
                      {children}
                    </code>

                  ) : (

                    <pre>
                      <code className={className}>
                        {children}
                      </code>
                    </pre>

                  );
                },
              }}
            >
              {message.content}
            </ReactMarkdown>

          )}

        </div>

        {!isUser && message.sources?.length > 0 && (
          <SourcePanel sources={message.sources} />
        )}

        {!isUser && (
          <div className="message-actions">

            <button
              onClick={copyMessage}
              title="Copy response"
            >

              {copied ? (

                <>
                  <Check size={14} />
                  Copied
                </>

              ) : (

                <>
                  <Copy size={14} />
                  Copy
                </>

              )}

            </button>

            {message.provider && (
              <span>
                Generated by{" "}
                {message.provider}
              </span>
            )}

          </div>
        )}

      </div>

    </div>
  );
}